---
- name: Get nerdctl completion
  command: "{{ bin_dir }}/nerdctl -n k8s.io  --insecure-registry  completion bash"
  changed_when: False
  register: nerdctl_completion
  check_mode: false

- name: Install nerdctl completion
  copy:
    dest: /etc/bash_completion.d/nerdctl
    content: "{{ nerdctl_completion.stdout }}"
    mode: 0644
